Mxonline/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url,include

import xadmin
from django.views.generic import TemplateView
from apps.users.views import LoginView,LogoutView,SendSmsView,DynamicLoginView,RegisterView
from apps.organizations.views import OrgView
#取消csrf_token的工具
from django.views.decorators.csrf import csrf_exempt

#关于静态文件图片的访问
from django.views.static import serve

#配置上传文件的路径
from Mxonline.settings import MEDIA_ROOT

urlpatterns = [
    # path('admin /', admin.site.urls),
    path('xadmin/', xadmin.site.urls),


    #下面两行二选一 template_name="index.html" 和 template_name="base.html" 二选一
    path('', TemplateView.as_view(template_name="index1.html"),name='index'),  #TemplateView 后面直接跟路径
    #path('', TemplateView.as_view(template_name="base.html"),name='index'),




    #账号登录的视图
    path('login/', LoginView.as_view(),name = "login"),  #其别名


    #注册
    path('register/', RegisterView.as_view(),name = "register"),  #其别名

    # 退出登录
    path('logout/', LogoutView.as_view(), name="logout"),  # name其别名


    #图片验证码
    url(r'^captcha/',include('captcha.urls')),

    #   服务器发送4位短信验证码
    url(r'^send_sms/',csrf_exempt(SendSmsView.as_view()),name="send_sms"), #接受验证码的接口

    # 接收到验证码、填写验证码、redis是否匹配、如果匹配点击登录
    path('d_login/', csrf_exempt(DynamicLoginView.as_view()), name="d_login"),


    #1、为了整理、上传的图片、我们把所有的上传文件放到media文件夹下面、并且为它创建url访问地址   在setting当中设置两行 151行 152行
    #2、设置了setting之后、依然是一个破图、显示不了
    #3、配置关于media中图片的访问
    #4、r'^media/(?P<path>.*)$' 的意思是取出media文件夹后面的文件把他放到path这个路径当中,
    #5、server 静态文件的访问url 地址， 这个地址是key:value的形式存储在 Media_root路径下面
    url(r'^media/(?P<path>.*)$',serve,{"document_root":MEDIA_ROOT}),


    # 课程机构
    # url(r'^org_list/',OrgView.as_view(), name = 'org_list'),
    url(r'^org/',include(('apps.organizations.urls',"organizations"),namespace='org')),

    #用户相关操作
    url(r'^op/', include(('apps.operation.urls', "operations"), namespace="op")),

    #课程列表页面开发
    url(r'^course/', include(('apps.courses.urls', "courses"), namespace="course")),

]

apps/courses/urls.py
from django.conf.urls import url

from apps.courses.views import CourseListView,CourseDetailView,CourseLessonView,CourseCommentsView,VideoView




urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name="list"),
    url(r'^(?P<course_id>\d+)/$', CourseDetailView.as_view(), name="detail"),
    url(r'^(?P<course_id>\d+)/lesson/$', CourseLessonView.as_view(), name="lesson"),
    url(r'^(?P<course_id>\d+)/comments/$', CourseCommentsView.as_view(), name="comments"),
    url(r'^(?P<course_id>\d+)/video/(?P<video_id>\d+)$', VideoView.as_view(), name="video"),

]

apps/operation/urls.py
from django.conf.urls import url

from apps.operation.views import AddFavView,CommentView

urlpatterns = [
    url(r'^fav/$', AddFavView.as_view(), name="fav"),
    url(r'^comment/$', CommentView.as_view(), name="comment")
]

apps/organizations/urls.py
from django.conf.urls import url
from apps.organizations.views import OrgView,AddAskView,OrgHomeView,OrgTeacherView,OrgDescView,OrgCourseView,TeacherListView
from django.urls import include, path

urlpatterns = [
    #机构页面的url
    url(r"^list/$",OrgView.as_view(),name = "list"),
    #咨询Url
    url(r"^add_ask/$",AddAskView.as_view(),name = "add_ask"),
    #组织机构详细页面 路由一
    #url(r'^(?P<org_id>\d+)/$',OrgHomeView.as_view(),name = "home"),
    #组织机构详细页面 路由二
    path('<int:org_id>/',OrgHomeView.as_view(),name = "home"),

    #机构教师列表
    url(r'^(?P<org_id>\d+)/teacher/$',OrgTeacherView.as_view(),name = "teacher"),
    #机构的介绍页
    url(r"^(?P<org_id>\d+)/desc/$",OrgDescView.as_view(),name = "desc"),

    #机构的课程页面
    url(r'^(?P<org_id>\d+)/course/$', OrgCourseView.as_view(), name="course"),

    #讲师列表页面
    url(r'^teachers/$', TeacherListView.as_view(), name="teachers"),
]

apps/courses/models.py
from datetime import datetime

from django.db import models

from apps.users.models import BaseModel
from apps.organizations.models import Teacher
from apps.organizations.models import CourseOrg

# from DjangoUeditor.models import UEditorField

#1. 设计表结构有几个重要的点
"""
实体1 <关系> 实体2
课程 章节 视频 课程资源
"""
#2. 实体的具体字段

#3. 每个字段的类型，是否必填


class Course(BaseModel):
    #外键这个课程属于哪个老师
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, verbose_name="讲师")

    #这个课程属于哪个机构  增加字段、课程是哪个机构的、这样会引起字段冗余、但是这样查询起来比较快、也是数据库调优的一种方式
    course_org = models.ForeignKey(CourseOrg, null=True, blank=True, on_delete=models.CASCADE, verbose_name="课程机构")

    name = models.CharField(verbose_name="课程名", max_length=50)
    desc = models.CharField(verbose_name="课程描述", max_length=300)
    learn_times = models.IntegerField(default=0, verbose_name="学习时长(分钟数)")
    degree = models.CharField(verbose_name="难度", choices=(("cj", "初级"), ("zj", "中级"), ("gj", "高级")), max_length=2)
    students = models.IntegerField(default=0, verbose_name='学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏人数')
    click_nums = models.IntegerField(default=0, verbose_name="点击数")
    notice = models.CharField(verbose_name="课程公告",max_length=300,default="")
    category = models.CharField(default=u"后端开发", max_length=20, verbose_name="课程类别")
    tag = models.CharField(default="", verbose_name="课程标签", max_length=10)
    youneed_know = models.CharField(default="", max_length=300, verbose_name="课程须知")
    teacher_tell = models.CharField(default="", max_length=300, verbose_name="老师告诉你")

    is_classics = models.BooleanField(default=False, verbose_name="是否经典")

    detail = models.TextField(verbose_name="课程详情")

    image = models.ImageField(upload_to="courses/%Y/%m", verbose_name="封面图", max_length=100)

    class Meta:
        verbose_name = "课程信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def lesson_nums(self):
        #显示课程的章节数
        return self.lesson_set.all().count()


class CourseTag(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="课程")
    tag = models.CharField(max_length=100, verbose_name="标签")

    class Meta:
        verbose_name = "课程标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.tag



class Lesson(BaseModel):
    '''
    章节表
    '''
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="课程")  #on_delete表示对应的外键数据被删除后，当前的数据应该怎么办
    name = models.CharField(max_length=100, verbose_name="章节名")
    learn_times = models.IntegerField(default=0, verbose_name="学习时长(分钟数)")

    class Meta:
        verbose_name = "课程章节"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Video(BaseModel):
    lesson = models.ForeignKey(Lesson, verbose_name="章节", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u"视频名")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟数)")
    url = models.CharField(max_length=1000, verbose_name=u"访问地址")

    class Meta:
        verbose_name = "视频"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(BaseModel):
    '''
    课程资源
    '''
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="课程")
    name = models.CharField(max_length=100, verbose_name=u"名称")
    file = models.FileField(upload_to="course/resourse/%Y/%m", verbose_name="下载地址", max_length=200)

    class Meta:
        verbose_name = "课程资源"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/org-detail-desc.html
{% extends 'org_base.html' %}
{% block title %}机构描述{% endblock %}

{% block right_form%}
<div class="right companycenter layout" >
        <div class="head">
            <h1>机构介绍</h1>
        </div>
        <div class="des">
            {{course_org.desc}}
        </div>
    </div>
{%endblock%}

templates/org-detail-homepage.html
{% extends 'org_base.html' %}
{% block title%}机构首页{%endblock%}

{% block right_form %}
<div class="right companycenter layout grouping" >
		<div class="head">
			<h1>全部课程</h1>
			<a class="green fr more" href="{% url 'org:course' course_org.id%}">查看更多  >  </a>
		</div>
		<div class="brief group_list">
            {% for course in all_courses %}

                <div class="module1_5 box">
                    <a href="course-detail.html"><img width="214" src="{{MEDIA_URL}}{{course.image}}"/></a>
                    <div class="des">
                        <a href="course-detail.html"><h2>{{ course.name }}</h2></a>
                        <span class="fl">课时：<i class="key">{{ course.learn_times }}</i></span>
                        <span class="fr">参加人数：{{ course.students }}</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">{{ course_org.name }}</span>
                         <span class="star fr  notlogin
                            " data-favid="13"  data-fav-type="4">
                            0
                        </span>
                    </div>
                </div>
            {% endfor %}

		</div>
	</div>
<div class="right companycenter layout" >
    <div class="head">
        <h1>机构教师</h1>
        <a class="green fr more" href="{% url 'org:teacher' course_org.id %}">查看更多  >  </a>
    </div>

    <div class="diarys">
        {% for teacher in all_teacher %}
            <div class="module5 share company-diary-box" style="padding:10px 0;">
            <div class="left">
                <img class="pic" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                <p>昵称：{{ teacher.name }}</p>
            </div>
            <div class="right">
                <div class="top">
                    <div class="fl">
                        <a href=""><h1>{{ teacher.work_position }}</h1></a>
                        <span>工作年限：{{ teacher.work_years }}</span>
                    </div>
                </div>
                <div class="middle" style="border-bottom:0;">{{ teacher.points }}</div>
            </div>
        </div>
        {% endfor %}
    </div>



</div>

<div class="right companycenter layout" >
    <div class="head">
        <h1>机构介绍</h1>
        <a class="green fr more" href="{% url 'org:desc' course_org.id %}">查看更多  >  </a>
    </div>
    <div class="cont">
        {{ course_org.desc }}
    </div>
</div>

{% endblock %}

templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}机构首页{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css'%}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js'%}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js'%}" type="text/javascript"></script>

</head>

<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">

                <div class="top">
				<div class="wp">
					<div class="fl">
                        <p>联系方式：<b>3333333333</b></p>
                    </div>
                    {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>yuanjia<img class="down fr" src="/static/images/top_down.png"/></dd>
                                <dt><img width="20" height="20" src="/static/media/image/2016/12/default_big_14.png"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="/static/media/image/2016/12/default_big_14.png"/></dt>
	                                <dd>
	                                    <h2>django</h2>
	                                    <p>yuanjia</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="usercenter-info.html">进入个人中心</a>
	                                <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    {% else %}

                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    {% endif %}

				</div>
			</div>


    <div class="middle companyheader">
        <div class="wp">
<!--            显示用户上传的照片-->
            <img class="fl" style="width: 112px;height: 103px" src="{{MEDIA_URL}}{{course_org.image}}"/>
            <div class="head fl">
                <h1>
                    {{course_org.name}}
                    {% if course_org.is_auth %}
                        <img src="{%static 'images/authentication.png'%}"/>
                    {% endif %}

                    {% if course_org.is_gold %}
                    <img src="{%static 'images/gold.png'%}"/>
                    {% endif %}
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                    <span class="precision company-credit" data-star-scope="5.0"></span>
                    <span class="key">5.0</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin
                 "data-favid="22" data-fav-type="1">
                 {% if has_fav %}已收藏{% else %}收藏{%endif%}
            </div>

        </div>
    </div>
			</div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'index'%}">首页</a>></li>
			<li><a href="{% url 'org:list'%}">课程机构</a>></li>
			<li>{% block path %}机构首页{% endblock %}</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{%ifequal current_page 'home'%}active2{%endifequal%}"><a href="{% url 'org:home' course_org.id%}">机构首页</a></li>
                <li class="{%ifequal current_page 'course'%}active2{%endifequal%}"><a href="{% url 'org:course' course_org.id %}">机构课程</a></li>
                <li class="{%ifequal current_page 'desc'%}active2{%endifequal%}"><a href="{% url 'org:desc' course_org.id %}">机构介绍</a></li>
                <li class="{%ifequal current_page 'teacher'%}active2{%endifequal%}"><a href="{% url 'org:teacher' course_org.id %}">机构讲师</a></li>
			</ul>
		</div>
<!--    </div>-->
{% block right_form %}

{% endblock %}


</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
</div>
<!--弹出省省市-->
<script src="{%static 'js/selectUi.js'%}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js'%}"></script>
<script src="{%static 'js/plugins/layer/layer.js'%}"></script>
<script src="{%static 'js/plugins/queryCity/js/public.js'%}" type="text/javascript"></script>

<script type="text/javascript" src="{%static 'js/plugins/jquery.raty.js'%}"></script>
<script src="{%static 'js/plugins/jquery.scrollLoading.js'%}"  type="text/javascript"></script>
<script src="{%static 'js/deco-common.js'%}"  type="text/javascript"></script>

<script type="text/javascript">
{% block custom_jss %}{% endblock %}
    //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url 'op:fav' %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
<!--                    如果判断未登录跳转到登陆页面-->
                    window.location.href="{% url 'login' %}";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$(document).ready(function() {
    $('.collectionbtn').on('click', function(){
        add_fav($(this), {{course_org.id}}, 2);
    });
});
$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '{%static 'images/'%}',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $(document).ready(function() {
        $('.jsFavBtn').on('click', function () {
            var type = $(this).attr('data-fav-type');
            if (type == '1') {
                favPraise($(this), 'fav', 1, '收藏');

            } else if (type == '3') {
                favPraise($(this), 'fav', 3);

            } else if (type == '11') {
                favPraise($(this), 'pra', 1);

            } else if (type == '4') {
                favPraise($(this), 'fav', 4);

            }
        });
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>

</body>
</html>